# version: '3.8'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3007:3007"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development
#     command: npm run dev


version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3007:3007"

